// Array of Indian proverbs (muhavare) and motivational thoughts
const thoughts = [
    "जितना के बाबू, उतना के झुंझुना",
    "आ बैल मुझे मार।",
    "ऊंट के मुंह में जीरा।",
    "नाच न जाने आंगन टेढ़ा।",
    "घर का भेदी लंका ढाए।",
    "डूबते को तिनके का सहारा।",
    "जब जागो तब सवेरा।",
    "हाथी के दांत खाने के और, दिखाने के और।",
    "आसमान से गिरा, खजूर में अटका।",
    "बंदर क्या जाने अदरक का स्वाद।",
    "थोथा चना बाजे घना।",
    "नौ सौ चूहे खा के बिल्ली हज को चली।",
    "सावन के अंधे को हर जगह हरियाली ही दिखती है।",
    "चोर की दाढ़ी में तिनका।",
    "लोहे को लोहे से काटा जाता है।",
    "जैसा बीज बोओगे, वैसा फल पाओगे।",
    "सांप भी मर जाए, और लाठी भी न टूटे।",
    "घर का जोगी जोगना, बाहर का साधू योगी।",
    "जैसा राजा, वैसी प्रजा।",
    "जिनके पास ज्ञान है, वही अमीर हैं।",
    "जहां चाह वहां राह।",
    "पानी में रहकर मगरमच्छ से बैर नहीं।",
    "लालच बुरी बला है।",
    "जितनी चादर हो, उतने ही पैर पसारो।",
    "हर चमकने वाली चीज सोना नहीं होती।",
    "अब पछताए होत क्या, जब चिड़िया चुग गई खेत।",
    "नाव में छेद हो तो दरिया पार नहीं कर सकते।",
    "समझदार को इशारा काफी।",
    "सब्र का फल मीठा होता है।",
    "काम खुद से शुरू करो।",
    "सपने उन्हीं के पूरे होते हैं, जो उन्हें पूरा करने के लिए मेहनत करते हैं।",
    "कर्म ही पूजा है।",
    "अकेला चना भाड़ नहीं फोड़ सकता।",
    "खुदा उसी की मदद करता है, जो खुद अपनी मदद करता है।",
    "जो गिरेगा वही उठेगा।",
    "जहां मेहनत वहां सफलता।",
    "सबसे बड़ी संपत्ति, शिक्षा है।",
    "लोहा गरम है, मारो हथौड़ा।",
    "दिया तले अंधेरा।",
    "खुद को सुधारो, दूसरों को सुधारना छोड़ो।",
    "पैसा पैसा जोड़े तो महल खड़ा हो।",
    "हर पत्थर भगवान नहीं होता।",
    "जैसा बोओगे, वैसा काटोगे।",
    "मन के हारे हार है, मन के जीते जीत।",
    "सब दिन एक समान नहीं होते।",
    "बिना मतलब की बातों में टांग अड़ाना।",
    "पल में माशा, पल में तोला।",
    "जो भाग्य में लिखा है, वह जरूर मिलेगा।",
    "जो गरजते हैं, वो बरसते नहीं।",
    "छोटी-छोटी चीजों का महत्व समझो।",
    "खुद की काबिलियत पर भरोसा रखो।",
    "जो सपने देखता है, वही उन्हें पूरा करता है।",
    "चालाकी से नहीं, मेहनत से जीत मिलती है।",
    "जहां चाह, वहां राह।",
    "अधजल गगरी छलकत जाए।",
    "भूत का क्या डर, भगवान का नाम लो।",
    "सब्र करने वाला कभी खाली हाथ नहीं रहता।",
    "Actions speak louder than words.",
    "A journey of a thousand miles begins with a single step.",
    "Rome wasn't built in a day.",
    "All that glitters is not gold.",
    "Better late than never.",
    "Time is money.",
    "Don't count your chickens before they hatch.",
    "The early bird catches the worm.",
    "A picture is worth a thousand words.",
    "When in Rome, do as the Romans do.",
    "Every cloud has a silver lining.",
    "Beauty is in the eye of the beholder.",
    "You can't judge a book by its cover.",
    "Practice makes perfect.",
    "Honesty is the best policy.",
    "Knowledge is power.",
    "Where there's a will, there's a way.",
    "An apple a day keeps the doctor away.",
    "Laughter is the best medicine.",
    "Actions have consequences.",
    "A watched pot never boils.",
    "Money can't buy happiness.",
    "You reap what you sow.",
    "The grass is always greener on the other side.",
    "It's never too late to start.",
    "What goes around comes around.",
    "Don't bite the hand that feeds you.",
    "You miss 100% of the shots you don't take.",
    "The pen is mightier than the sword.",
    "What doesn't kill you makes you stronger.",
    "Life is like a box of chocolates – you never know what you're gonna get.",
    "There's no place like home.",
    "A fool and his money are soon parted.",
    "The squeaky wheel gets the grease.",
    "If it ain't broke, don't fix it.",
    "You can lead a horse to water, but you can't make it drink.",
    "Don't put all your eggs in one basket.",
    "Beggars can't be choosers.",
    "The best things in life are free.",
    "It's better to give than to receive.",
    "Two wrongs don't make a right.",
    "What you see is what you get.",
    "A bird in the hand is worth two in the bush.",
    "Better safe than sorry.",
    "Curiosity killed the cat.",
    "You are what you eat.",
    "If you want something done right, do it yourself.",
    "A stitch in time saves nine.",
    "The apple doesn't fall far from the tree.",
    "Don't cry over spilled milk.",
    "Blood is thicker than water.",
    "A friend in need is a friend indeed.",
    "A problem shared is a problem halved.",
    "If the shoe fits, wear it.",
    "You can't please everyone.",
    "Every dog has its day.",
    "Fortune favors the bold.",
    "Haste makes waste.",
    "The road to hell is paved with good intentions.",
    "Time heals all wounds.",
    "All's fair in love and war.",
    "Nothing ventured, nothing gained.",
    "Don't sweat the small stuff.",
    "Silence is golden.",
    "Make hay while the sun shines.",
    "A penny saved is a penny earned.",
    "If it's meant to be, it will be.",
    "Don't bite off more than you can chew.",
    "A house is not a home without love.",
    "Love conquers all.",
    "There is no such thing as a free lunch.",
    "The road less traveled is the best one.",
    "Don't put off until tomorrow what you can do today.",
    "If you can't stand the heat, get out of the kitchen.",
    "Don't take life too seriously.",
    "Good things come to those who wait.",
    "Every rose has its thorn.",
    "What's done is done.",
    "Better to have loved and lost than never to have loved at all.",
    "Ignorance is bliss.",
    "You win some, you lose some.",
    "All good things must come to an end.",
    "If at first you don't succeed, try, try again.",
    "Keep your friends close, but your enemies closer.",
    "A little knowledge is a dangerous thing.",
    "Don't burn bridges.",
    "Life's too short to be anything but happy.",
    "Life is what happens when you're busy making other plans.",
    "If you don't ask, you don't get.",
    "The best revenge is massive success.",
    "Don't put your all into something that won't give back.",
    "Where there's smoke, there's fire.",
    "A chain is only as strong as its weakest link.",
    "The only thing to fear is fear itself.",
    "Live and let live."      
  ];
  
// Get references to the DOM elements
const thoughtElement = document.getElementById('thought');
const button = document.getElementById('new-thought-btn');

// Function to display a random thought
function displayRandomThought() {
  const randomIndex = Math.floor(Math.random() * thoughts.length);
  thoughtElement.textContent = thoughts[randomIndex];
}

// Display a random thought when the page loads
displayRandomThought();

// Add an event listener to the button
button.addEventListener('click', displayRandomThought);